### ISSUE TITLE
wrapcheck: Unexpected package creation during export data loading

### ISSUE THREAD

**Issue by rledisez** [tomarrell/wrapcheck#30]
With some specific (generic) code, this error appear in some circumstances:
`wrapcheck: Unexpected package creation during export data loading`

Updating the dependency `x/tools` to version 0.1.11 fix the issue

https://github.com/tomarrell/wrapcheck/blob/213318509af6a003be2be752da826d269149ba4d/go.mod#L9

**Comment by tomarrell** [comment]
Thanks a lot for the report. I'll it updated and push a new version shortly. :+1:
