### ISSUE TITLE
HTTP Handlers Errors

### ISSUE THREAD

**Issue by 1995parham** [tomarrell/wrapcheck#33]
Most of the go http frameworks has the error as return in their handlers, so we can add them into the ignore pattern if you agree.

**Comment by tomarrell** [comment]
G'day @1995parham, would you be able to describe better the issue you're having? Currently your request is a little vague.

**Comment by 1995parham** [comment]
Sure, for example on [gofiber](https://github.com/gofiber/) we have:

```go
    app.Get("/", func(c *fiber.Ctx) error {
        return c.SendString("Hello, World 👋!")
    })
```

I think, it doesn't a good idea to wrap its error.

**Comment by tomarrell** [comment]
You should already be able to have wrapcheck refrain from reporting errors like this using the configuration parameters. Is that not working for you?

**Comment by 1995parham** [comment]
Yes, exactly we are using that configuration. The only issue is about for us to repeat the default values too. So if we can somehow add these into the defaults or append the configuration to them it would be great.

**Comment by tomarrell** [comment]
I'm sorry, I don't think it makes sense to add these to the default configuration, as this practice wouldn't be scalable for all the libraries out there.

Yes, you need to add the defaults yourself if you are going to configure it. This enables people to easily override the default set.
