### ISSUE TITLE
Ability to ignore specific error types

### ISSUE THREAD

**Issue by mwgamble** [tomarrell/wrapcheck#45]
I'm creating a CLI app, and I'm using a package named `promptui` to display fancy prompts. If a user presses `Ctrl+D` or `Ctrl+C` while a prompt is active, this package returns specific error types to indicate this. These error types are statically declared, and I don't have any need to wrap these errors before passing them on.

It would be nice if there was a way to exclude specific errors, rather than any error from a given package.

**Comment by tomarrell** [comment]
This should be doable with the `ignoreSigRegexps` configuration option. You can specify the type in the signature to your desired level of specificity.
