### ISSUE TITLE
Lint error from internal packages

### ISSUE THREAD

**Issue by maguro** [tomarrell/wrapcheck#53]
I have functions that reside in an internal package that return `error`.  I am getting the "error returned from external package is unwrapped" error even though it's internal.  For example:

    foo/stats.go:43:10: error returned from external package is unwrapped: sig: func 
    acme.com/foo/internal.Bar(ctx context.Context, key string) (ok bool, err error)

**Comment by tomarrell** [comment]
Is this call through an interface?
