### ISSUE TITLE
feature reuqest: extra option to extend, rather than replace, `ignoreSigs`

### ISSUE THREAD

**Issue by matthewhughes934** [tomarrell/wrapcheck#54]
I have a use-case where I would like to add another signature to be ignored by `wrapcheck`[1], currently this means adding it to `ignoreSigs` which will stomp any of the defaults, so to keep current behaviour I need to:

* Copy the current defaults to my config under `ignoreSigs`
* Add another entry for my new signature

I find the current defaults very helpful, so this means I now need to manually keep my list in sync (e.g. if any new values are added as default I will need to also add them to my config).

**Request**: I was wondering if you would be open to accepting a change that adds a new config option like `extraIgnoreSigs` to address this, like:

```yaml
extraIgnoreSigs:
    # ignore all the everything under `ignoreSigs` (or the defaults if that doesn't exist) and additionally:
    - SomeSpecialFunc(
    - SomeOtherFunc(
```

Currently the same behaviour would require a config like:

```yaml
ignoreSigs:
# default values
- .Errorf(
- errors.New(
- errors.Unwrap(
- errors.Join(
- .Wrap(
- .Wrapf(
- .WithMessage(
- .WithMessagef(
- .WithStack(
# my extra bits
- SomeSpecialFunc(
- SomeOtherFunc(
```

I'd be happy to try and get this change up if there's interest

[1] My case was for ignoring [`google.golang.org/grpc/status.Error`](https://pkg.go.dev/google.golang.org/grpc/status#Error), note that package also has `google.golang.org/grpc/status.Errorf` which is ignored by the `.Errorf(` sig in the default list, so I was also wondering if `.Error(` functions might be considered for inclusion in the default list?

**Comment by hugowetterberg** [comment]
Seconded, was looking through the issues to see if somebody else had raised this. Looks like the maintainer has been busy with other stuff for a while (which is completely fine :smiley:), so might be a good idea to just submit a PR for review.

Are you still interested in creating a PR @matthewhughes934?

**Comment by matthewhughes934** [comment]
> Seconded, was looking through the issues to see if somebody else had raised this. Looks like the maintainer has been busy with other stuff for a while (which is completely fine 😃), so might be a good idea to just submit a PR for review.

:+1: I created https://github.com/tomarrell/wrapcheck/pull/56

**Comment by tomarrell** [comment]
Thanks a lot for the PR! I'll take a look at it shortly and get back to you. 👍
